language: generic
sudo: required
services:
  - docker

befire_install:
  - docker build -t edskrnd80/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run edskrnd80/react-test npm test

after_success:
  - docker build -t edskrnd80/multi-client ./client
  - docker build -t edskrnd80/multi-nginx ./nginx
  - docker build -t edskrnd80/multi-server ./server
  - docker build -t edskrnd80/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push edskrnd80/multi-client
  - docker push edskrnd80/multi-nginx
  - docker push edskrnd80/multi-server
  - docker push edskrnd80/multi-worker

